FROM python:2.7

WORKDIR /app_in_docker

COPY requirements.txt /app_in_docker/requirements.txt

RUN pip install -r requirements.txt

COPY . /app_in_docker

ENTRYPOINT ["gunicorn"]
CMD ["wsgi_default_local_docker:app","--bind","0.0.0.0:8100"]
