FROM python:3.6

WORKDIR /apiviz_backend_in_docker

COPY requirements.txt /apiviz_backend_in_docker/requirements.txt

RUN pip install -r requirements.txt

COPY . /apiviz_backend_in_docker

ENTRYPOINT ["gunicorn"]
CMD ["wsgi_prod:app","--bind","0.0.0.0:8100"]
